# Site settings
title: About Me
description: Who I am?
baseurl: "https://hackingprofessional.github.io/about" 
url: "https://hackingprofessional.github.io" 

# User settings
username: Gerardo Eliasib
user_description: My name is Gerardo Eliasib, I am an IT Security Analyst and Ethical Hacker, for passion, vocation and profession.  I have worked professionally as a web programmer, Analyst NOC/SOC and pentester; I have participated in the realization of modern phising campaigns and prevention of computer risks in a work environment.  For now, this blog mainly documents a large part of the knowledge I have acquired in my professional development and independent projects that I do extensively in the field of technology.  I began to be interested in computer security since I was 13 years old, the happiness and the sensation of manipulating the normal functioning of video games for my own benefit was the beginning to enter this important branch of computer science.  In order to acquire knowledge in a self-taught way I perform security audits, vulnerabilities and pentesting in HackTheBox, which is an online platform that allows you to test your hacking and pentesting skills.
user_title: Cybersecurity Analyst
email: gerueda6@misena.edu.co
#twitter_username: lorem_ipsum
github_username:  HackingProfessional
gplus_username:  gerh002

# Google-analytics
google-analytics:
  id: "UA-136401706-1"

exclude: ['package.json', 'src' , 'node_modules']
